<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="jumbotron jumbotron-home-page text-center">
    <div class="lead-box">
        <h1 class="text-primary">Laminas Project, the enterprise-ready PHP Framework and components</h1>

        <h2 class="text-primary">
            A community-supported, open source continuation of Zend Framework.
        </h2>
    </div>
</div>

<div class="container">
    <div class="row row-cols-1 row-cols-md-3">
        <div class="col mb-4">
            <div class="card h-100 border border-components rounded">
                <div class="card-header bg-components text-white w-auto">
                    Components and MVC
                </div>

                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Enterprise-ready PHP components and MVC framework</h5>

                    <p class="card-text">
                        Components for any PHP application, including dependency injection,
                        event dispatchers, input validation and filtering, pagination and
                        navigation, feed generation and parsing, and much, much more.
                    </p>

                    <p class="card-text">
                        A standards-based, event-driven MVC framework with a flexible workflow.
                    </p>

                    <a class="btn btn-components mt-auto text-white" href="https://docs.laminas.dev">
                        Laminas documentation
                    </a>
                </div>
            </div>
        </div>

        <div class="col mb-4">
            <div class="card h-100 border border-expressive rounded">
                <div class="card-header bg-expressive text-white">
                    Mezzio
                </div>

                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">PHP Middleware in Minutes</h5>

                    <p class="card-text">
                        Build PHP middleware applications, using the
                        PSR-7 (HTTP Messages) and PSR-15 (HTTP Request Handlers)
                        specifications, using a variety of routing and
                        templating options, and the dependency injection
                        container you prefer.
                    </p>

                    <a class="btn btn-expressive mt-auto text-white" href="https://docs.mezzio.dev">
                        Mezzio documentation
                    </a>
                </div>
            </div>
        </div>

        <div class="col mb-4">
            <div class="card h-100 border border-apigility rounded">
                <div class="card-header bg-apigility text-white">
                    API Tools
                </div>

                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Build Beautiful RESTful APIs</h5>

                    <p class="card-text">
                        Build RESTful APIs using standards such as Hypertext
                        Application Language and Problem Details for HTTP APIs,
                        and provide validation, authentication, authorization,
                        and versioning right out of the box!
                    </p>

                    <a class="btn btn-apigility mt-auto text-white" href="https://api-tools.getlaminas.org">
                        API Tools documentation
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mb-4">
    <div class="card text-white text-center support-banner">
        <div class="card-body">
            <h1 class="card-title">Donate</h1>
            <p class="card-text">Support Laminas Developers Directly</p>
            <a href="<?= $this->url('app.support') ?>" class="btn btn-secondary">Support Laminas</a>
        </div>
    </div>
</div>

<div class="container">
    <div class="card text-center">
        <div class="card-body">
            <h4 class="card-title">Commercial Vendors</h4>
            <p class="card-text">
                Laminas Projects are supported by these commercial vendors.
            </p>

            <div class="container">
                <div class="row align-items-center justify-content-center">
                <?php foreach ($commercialVendors as $commercialVendor): ?>
                    <div class="col-12 col-sm-6 col-md-4 col-lg-2">
                        <img class="img-fluid" src="<?= $this->escapeHtmlAttr($commercialVendor['logo']) ?>" alt="<?= $this->escapeHtmlAttr($commercialVendor['name']) ?>">
                    </div>
                <?php endforeach ?>
                </div>
            </div>

            <div class="mt-4">
                <a href="<?= $this->url('app.commercial-vendor-program') ?>" class="btn btn-secondary text-white">Find out more!</a>
            </div>
        </div>
    </div>
</div>
