<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var string $lastUpdated
 * @var array $repositoryData
 * @var string $search
 * @var array<array-key, string>|null $status
 */

use App\Enums\MaintenanceStatusEnum;
use App\Handler\MaintenanceOverviewHandler;

$this->layout('layout::default', ['title' => 'Current Maintenance Status of Laminas & Mezzio Packages']);

const GITHUB_URL = 'https://github.com/';

$this->start('styles');
$this->insert('blog::styles');
$this->stop();

$this->push('scripts');
$this->insert('blog::scripts');
$this->end();

?>
<div id="maintenance-overview" class="container">
    <div class="row mt-5">
        <div class="col">
            <h1 class="fw-bolder mb-5">Current Maintenance Status of Laminas & Mezzio Packages</h1>
        </div>
    </div>

    <div>
        <p>
            The page below intends to provide a fast, accessible way to examine every package at a glance.
            It provides a column for each subproject: Mezzio, Laminas Components, Laminas MVC and API Tools.
            The page is automatically refreshed daily and is publicly available.
        </p>
        <p>
            Below is the meaning of each status. The non-active statuses also include the date when they were set and the TSC md file where they were discussed
        </p>
    </div>

    <div id="repository-legend">
        <div class="legend-item">
            <div class="repo-properties">
                <p class="repo-property-name">Maintenance Mode</p>
                <p class="repo-property-value active">active</p>
            </div>
            <p class="repo-legend-text">The repository is actively being supported</p>
        </div>

        <div class="legend-item">
            <div class="repo-properties">
                <p class="repo-property-name">Maintenance Mode</p>
                <p class="repo-property-value security-only">maintenance-only</p>
            </div>
            <p class="repo-legend-text">The repository is only receiving support for bugs and security features</p>
        </div>

        <div class="legend-item">
            <div class="repo-properties">
                <p class="repo-property-name">Maintenance Mode</p>
                <p class="repo-property-value security-only">security-only</p>
            </div>
            <p class="repo-legend-text">The repository is only receiving critical security support</p>
        </div>

        <div class="legend-item">
            <div class="repo-properties">
                <p class="repo-property-name">Maintenance Mode</p>
                <p class="repo-property-value discontinued">discontinued</p>
            </div>
            <p class="repo-legend-text">The repository is no longer being supported</p>
        </div>
    </div>

    <div class="container my-3 g-0">
        <div class="row flex-lg-row">
            <div class="col d-flex justify-content-between">
                <button class="btn border-primary d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#statusSearchBar" aria-controls="statusSearchBar" aria-expanded="true" aria-label="Toggle search bar">
                    <span><i class="bi bi-list"></i></span>
                </button>

                <div class="col-lg-3 d-flex input-group">
                    <input type="text" id="package-search" class="form-control mr-sm-2" aria-label="Search" aria-describedby="package-search-btn" value="<?= $search ?>">
                    <button id="package-search-btn" class="btn border-primary my-sm-0" type="button"><i class="bi bi-search"></i></button>
                </div>
            </div>

            <div class="col-lg-9 d-lg-flex gap-2 collapse <?php if ($status) : ?>show<?php endif;?>" id="statusSearchBar">
                <?php foreach (MaintenanceStatusEnum::cases() as $case): ?>
                    <button class="btn btn-outline-primary mt-2 mt-lg-0 status-button<?php if ($status !== null && in_array($case->value, $status)) : ?> active<?php endif ?>" data-value="<?= $case->value ?>"><?= $case->label() ?></button>
                <?php endforeach ?>

                <?php if ($status || $search) : ?>
                    <button id="clear-filters-button" type="button" class="btn btn-outline-danger mt-2 mt-lg-0">Clear <i class="bi bi-x-circle"></i></button>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="repository-container">
        <?php foreach($repositoryData as $organization => $orgData): ?>
            <?php $githubOrg = $organization !== 'laminas-mvc' ? $organization : 'laminas' ?>
            <div class="repository-organization <?= $organization ?> rounded-4">
                <h1><?= MaintenanceOverviewHandler::GITHUB_ORGANIZATIONS[$organization] ?? $organization ?></h1>
                <div class="repository-card-container">
                    <?php
                    /** @var array $data */
                    foreach($orgData as $data) :
                        ?>
                        <div class="card repository-card">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a target="_blank"
                                       href="<?= sprintf(
                                           '%s%s/%s',
                                           GITHUB_URL,
                                           $githubOrg,
                                           $data['name']
                                       )
                                       ?>">
                                        <?= $data['name'] ?>
                                    </a>
                                </h5>

                                <img class="mb-2" src="
                                <?= sprintf(
                                        'https://img.shields.io/packagist/dependency-v/%s/%s/php?style=social',
                                        $githubOrg,
                                        $data['name']
                                ) ?>" alt="supported-php-versions">

                                <?php
                                $badgeLabel  = null;
                                $badgeValue  = null;
                                $minutesDate = null;
                                $minutesFile = null;
                                $minutesUrl  = null;
                                /** @var array $property */
                                foreach ($data['properties'] as $property) {
                                    if ($property['property_name'] === 'maintenance-mode') {
                                        $badgeLabel = ucwords(str_replace('-', ' ', $property['property_name']));
                                        $badgeValue = $property['value'];
                                    }

                                    if ($property['property_name'] === 'maintenance-mode-date') {
                                        $minutesDate = $property['value'];
                                    }

                                    if ($property['property_name'] === 'maintenance-mode-minutes') {
                                        $minutesFile = $property['value'];
                                        $minutesUrl  = sprintf(
                                            'https://github.com/%s/technical-steering-committee/blob/main/meetings/minutes/%s',
                                                $githubOrg,
                                            $minutesFile
                                        );
                                    }
                                }
                                ?>

                                <?php if ($badgeLabel !== null) : ?>
                                    <div class="repo-properties">
                                        <div class="repo-properties">
                                            <p class="repo-property-name">
                                                <?= $badgeLabel ?>
                                            </p>
                                            <p class="repo-property-value <?= $badgeLabel . ' ' . $badgeValue ?>"><?= $badgeValue ?></p>
                                        </div>
                                    </div>
                                <?php endif; ?>

                                <?php if ($minutesDate !== null) : ?>
                                    <p class="repository-data-text">
                                        Maintenance mode changed on: <?= $minutesDate ?>.
                                    </p>
                                    <?php if ($minutesFile !== null) : ?>
                                        <p class="repository-data-text">
                                            See <a href="<?= $minutesUrl ?>" target="_blank">
                                                <?= $minutesFile ?>
                                            </a>
                                        </p>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <p id="repository-last-updated">Last update: <?= $lastUpdated ?></p>
    <p>
        There is also a JSON version
        <a href="<?= $this->url('app.maintenance-status') ?>" target="_blank">here</a>.
        It contains the full list of properties for each package. Note that the properties differ between organizations.
    </p>
</div>
