<?php $this->layout('layout::default', ['title' => 'Support Laminas']) ?>

<div class="container">
    <div class="row mt-5">
        <div class="col">
            <h1>Support Laminas</h1>
        </div>
    </div>

    <div class="row align-items-start mt-5">
        <div class="col-md-8 col-sm-12 order-2 order-sm-1 mt-5 mt-s-0 mt-md-0 mt-lg-0 mt-xl-0">
            <h2>Sponsor Laminas Development</h2>

            <p>
                The Laminas Project is a <a
                href="https://opensource.org/licenses/BSD-3-Clause">BSD-3-Clause licensed</a>
                open source project and free to use.
                <br>
                The framework and all components are primarily developed and
                maintained by independent developers on a community-driven
                basis. Maintenance and feature development cost a lot of time and effort.
            </p>

            <p>
                You can actively support development by donations. This allows
                us to develop and maintain new features for the project and your own
                applications.
            </p>

            <p>
                <a href="https://crowdfunding.lfx.linuxfoundation.org/projects/laminas-project"
                   class="btn btn-secondary">
                    Become a sponsor via LXF Crowdfunding <i class="fas fa-chevron-right"></i>
                </a>
            </p>
        </div>

        <div class="col-md-4 col-sm-12 order-1 order-sm-2">
            <div class="bg-white border border-mvc p-4">
                <a href="https://crowdfunding.lfx.linuxfoundation.org/projects/laminas-project" class="text-mvc">
                    <img class="img-fluid" src="/images/lxf-crowdfunding.svg">
                    Support Laminas Developers Directly
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-start mt-5">
        <div class="col-md-8 col-sm-12 order-2 order-sm-1 mt-5 mt-s-0 mt-md-0 mt-lg-0 mt-xl-0">
            <h2>Commercial Vendor Program</h2>
            <p>
                Commercial companies and organisations that wish to support the ongoing development and maintenace of
                the Laminas projects can apply to join our new commercial vendor program
            </p>
        </div>

        <div class="col-md-4 col-sm-12 order-1 order-sm-2">
            <a class="btn btn-secondary w-100 p-4" href="<?= $this->url('app.commercial-vendor-program') ?>">
                Find out more
            </a>
        </div>
    </div>
</div>
