<?php $this->layout('layout::default', ['title' => 'Support Laminas']) ?>

<div class="container">
    <div class="row mt-5">
        <div class="col">
            <h1>Support Laminas</h1>
        </div>
    </div>

    <div class="row align-items-start mt-5">
        <div class="col-md-8 col-sm-12 order-2 order-sm-1 mt-5 mt-s-0 mt-md-0 mt-lg-0 mt-xl-0">
            <h2>Sponsor Laminas Development</h2>
            <p>
                The Laminas Project is an BSD 3-Clause licensed open source
                project and free to use.<br>
                The framework with all components is primarily developed and
                maintained by independent developers on a community driven
                basis. This costs a lot of time and effort.
            </p>
            <p>
                You can actively support the development by donations. This
                allows to develop and maintain new features for the project and
                also your own applications.
            </p>
            <p>
                <a href="https://funding.communitybridge.org/projects/laminas-project"
                   class="btn btn-secondary">
                    Become sponsor via CommunityBridge Funding
                </a>
            </p>
        </div>
        <div class="col-md-4 col-sm-12 order-1 order-sm-2">
            <div class="support-banner">
                <a href="https://funding.communitybridge.org/projects/laminas-project">
                    <img src="https://funding.communitybridge.org/assets/cb-f-horizontal-white.svg">
                    Support Core Developers Directly
                </a>
            </div>
        </div>
    </div>
</div>
