<?php $this->layout('layout::default', ['title' => 'Become a Sponsor']) ?>

<div class="jumbotron jumbotron-fluid text-center">
    <h1>Become a Sponsor</h1>
</div>

<div class="container-fluid">
    <div class="row justify-content-center"><div class="col-sm-8 col-xs-12 card-deck">
        <div class="card"><div class="card-body">
            <h2 class="card-title">Why Become a Sponsor?</h2>

            <p class="card-text">
                Over the years, Zend Framework has seen wide adoption across the
                PHP ecosystem, with an emphasis on the Enterprise market. How much
                adoption? As of April 2019, <strong>over 400 MILLION</strong>
                lifetime downloads of all packages, representing a four-fold increase
                over the last two years alone! It has formed the basis of numerous
                business applications and services including eCommerce platforms,
                content management, healthcare systems, entertainment platforms and
                portals, messaging services, APIs, and many others.
            </p>

            <p class="card-text">
                The Laminas Project aims to continue that mission. We want to ensure that
                the code is continuously maintained and improved for the lifetime of your
                applications, and that you will always have an experienced pool of developers
                to choose from.
            </p>

            <p class="card-text">
                If you want to help in this mission via corporate sponsorship, please fill
                out the form below, and we will contact you to discuss the
                possibilities.
            </p>
        </div></div>
    </div></div>

    <div class="row justify-content-center mt-5">
        <div class="col card"><div class="card-body"><div class="card-text">
            <h2>Form goes here</h2>
        </div></div></div>
    </div>
</div>
