<?php $this->layout('layout::default', ['title' => 'Thank You']) ?>

<div class="jumbotron jumbotron-join-thank-you text-center">
    <div class="lead-box">
        <h1 class="text-primary">
            Thank You!</h1>
        <h2 class="text-primary">
            We will be in contact with you soon!
        </h2>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center ">
        <div class="col-sm-8 col-xs-12 text-center">
            <p class="card-text ">We will be in contact with you soon!</p>
        </div>
    </div>
</div>