<?php $this->layout('layout::default', ['title' => 'Thank You']) ?>

<div class="jumbotron jumbotron-fluid text-center">
    <h1>Thank You!</h1>
</div>

<div class="container-fluid">
    <div class="row justify-content-center"><div class="col-sm-8 col-xs-12 card-deck">
        <div class="card"><div class="card-body">
            <p class="card-text">We will be in contact with you soon!</p>
        </div></div>
    </div></div>
</div>
