<?php $this->layout('layout::default', ['title' => 'Become a Member']) ?>

<div class="jumbotron jumbotron-fluid text-center">
    <h1>Become a Member</h1>
</div>

<div class="container-fluid">
    <div class="row justify-content-center"><div class="col-sm-8 col-xs-12 card-deck">
        <div class="card"><div class="card-body">
            <h2 class="card-title">Why Become a Member?</h2>

            <p class="card-text">
                Over the years, Zend Framework has seen wide adoption across the
                PHP ecosystem, with an emphasis on the Enterprise market. How much
                adoption? As of April 2019, <strong>over 400 MILLION</strong>
                lifetime downloads of all packages, representing a four-fold increase
                over the last two years alone! It has formed the basis of numerous
                business applications and services including eCommerce platforms,
                content management, healthcare systems, entertainment platforms and
                portals, messaging services, APIs, and many others.
            </p>

            <p class="card-text">
                The Laminas Project aims to continue that mission. We want to ensure that
                the code is continuously maintained and improved for the lifetime of your
                applications.
            </p>

            <p class="card-text">
                If you are interested in learning more about the benefits of
                becoming a member, please fill out the form below.
            </p>
        </div></div>
    </div></div>

    <div class="row justify-content-center mt-5 mb-5"><div class="col-sm-8 col-xs-12 card-deck">
        <div class="card"><div class="card-body">
            <form action="https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input class="form-control" id="first_name" maxlength="40" name="first_name" type="text" />
                </div>

                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input class="form-control" id="last_name" maxlength="80" name="last_name" type="text" />
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input class="form-control" id="email" maxlength="80" name="email" type="email" />
                </div>

                <div class="form-group">
                    <label for="company">Company</label>
                    <input class="form-control" id="company" maxlength="40" name="company" type="text" />
                </div>

                <div class="form-group">
                    <label for="title">Title</label>
                    <input class="form-control" id="title" maxlength="40" name="title" type="text" />
                </div>

                <button class="btn btn-primary float-right" type="submit" name="submit">Submit</button>

                <input type="hidden" id="Campaign_ID" name="Campaign_ID" value="7012M000001iJaa">
                <input type="hidden" name="oid" value="00D41000000cNi0">
                <input type="hidden" name="retURL" value="https://getlaminas.org/about/join/thank-you">
                <input type="hidden" name="debug" value="1" />
                <input type="hidden" name="debugEmail" value="matthew@weierophinney.net" />
            </form>
        </div></div>
    </div></div>
</div>
