<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 */

$this->layout('layout::default', ['title' => 'Technical Steering Committee']);
?>

<div class="hero-container mb-4">
    <div class="hero-box text-center">
        <h1>Technical Steering Committee</h1>
    </div>
</div>

<div class="container">
    <div class="row align-items-start">
        <div class="col-md-8 col-sm-12 order-2 order-sm-1 mt-5 mt-s-0 mt-md-0 mt-lg-0 mt-xl-0">
            <p>
                The Laminas Project is governed by its Technical Steering
                Committee (TSC) members, under a technical charter with the
                Linux Foundation. The canonical location of the TSC charter and
                any existing amendments, as well as the list of TSC members, is
                kept under the Laminas Project technical-steering-committee
                repository on GitHub.
            </p>

            <ul>
                <li><a href="https://github.com/laminas/technical-steering-committee/blob/master/CHARTER.md">TSC charter</a></li>
                <li><a href="https://github.com/laminas/technical-steering-committee/blob/master/MEMBERS.md">TSC members</a></li>
            </ul>
        </div>
    </div>
</div>

