<?php $this->layout('layout::default', ['title' => 'Security Advisories']) ?>

<div class="container">
    <div class="row align-items-start mt-5">
        <div class="col-md-8 col-sm-12 order-2 order-sm-1 mt-5 mt-s-0 mt-md-0 mt-lg-0 mt-xl-0">
            <h2>Security Advisories</h2>
            <h3>Vulnerabilities reported against the Laminas Project, and recommendations for mitigation</h3>

            <div class="list-group">
            <?php if ($tot > 0) : ?>
                <?php foreach ($advisories as $key => $advisory) : ?>
                    <a class="list-group-item" href="/security/advisory/<?= basename($key, '.md') ?>">
                        <h4 class="list-group-item-heading"><i class="fa fa-bug"></i>&nbsp;<?= $advisory['title'] ?></h4>
                        <p class="list-group-item-text">Published <?= date('Y-m-d', $advisory['date']) ?></p>
                    </a>
                <?php endforeach ?>
            <?php else : ?>
                <h4>No advisories available at this time</h4>
            <?php endif ?>
            </div>

            <div class="spacing"></div>
            <div class="hline"></div>

            <?php if ($tot > 0) : ?>
            <ul class="pager">
                <li class="previous<?= $prev ? '' : ' disabled' ?>"><a href="<?= $prev ? '?page=' . $prev : '#' ?>"><i class="fa fa-chevron-left"></i>&nbsp;Previous</a>
                </li>
                <li><strong class="text-info"><?php printf("Page %d/%d", $page, $tot) ?></strong></li>
                <li class="next<?= $next ? '' : ' disabled' ?>"><a href="<?= $next ? '?page=' . $next : '#' ?>">Next&nbsp;<i class="fa fa-chevron-right"></i></a></li>
            </ul>
            <?php endif ?>
        </div>

        <div class="col-md-4 col-sm-12 order-1 order-sm-2">
        <?php $this->insert('security::menu') ?>
        </div>
    </div>
</div>
