<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template                                 $this
 * @var array<array-key, array{title: string, date: DateTimeInterface}> $advisories
 * @var int                                                             $tot
 * @var int                                                             $page
 * @var int                                                             $prev
 * @var int                                                             $next
 */

$this->layout('layout::default', ['title' => 'Security Advisories']);
?>

<div class="container">
    <div class="row align-items-start mt-5">
        <div class="col-md-8 col-sm-12 order-2 order-sm-1 mt-5 mt-s-0 mt-md-0 mt-lg-0 mt-xl-0">
            <h2>Security Advisories</h2>
            <h3>Vulnerabilities reported against the Laminas Project, and recommendations for mitigation</h3>

            <div class="list-group">
            <?php if ($tot > 0) : ?>
                <?php foreach ($advisories as $key => $advisory) : ?>
                    <a class="list-group-item" href="<?= $this->url('security.advisory', ['advisory' => basename($key, '.md')]) ?>">
                        <h4 class="list-group-item-heading"><?= $advisory['title'] ?></h4>
                        <p class="list-group-item-text">Published <?= (new DateTimeImmutable($advisory['date']))->format('Y-m-d') ?></p>
                    </a>
                <?php endforeach ?>
            <?php else : ?>
                <h4>No advisories available at this time</h4>
            <?php endif ?>
            </div>

            <div class="spacing"></div>
            <div class="hline"></div>

            <?php if ($tot > 1) : ?>
            <nav arial-label="Security advisory page navigation">
                <ul class="pagination mt-4 justify-content-center">
                    <li class="page-item previous<?= $prev ? '' : ' disabled' ?>">
                        <a class="page-link" href="<?= $prev ? '?page=' . $prev : '#' ?>">
                            <i class="bi-arrow-left-square-fill"></i>
                            Previous
                        </a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="#">
                            Page <?= $page ?> of <?= $tot ?>
                        </a>
                    </li>
                    <li class="page-item next<?= $next ? '' : ' disabled' ?>">
                        <a class="page-link" href="<?= $next ? '?page=' . $next : '#' ?>">
                            Next
                            <i class="bi-arrow-right-square-fill"></i>
                        </a>
                    </li>
                </ul>
            </nav>
            <?php endif ?>
        </div>

        <div class="col-md-4 col-sm-12 order-1 order-sm-2">
        <?php $this->insert('security::menu') ?>
        </div>
    </div>
</div>
