<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var string                          $body
 * @var string                          $date
 */

$this->layout('layout::default', ['title' => 'Security Advisories']);
?>

<div class="container">
    <div class="row align-items-start mt-5">
        <div class="col-md-8 col-sm-12 order-2 order-sm-1 mt-5 mt-s-0 mt-md-0 mt-lg-0 mt-xl-0">
            <?= $body ?>

            <div class="spacing"></div>
            <div class="hline"></div>

            <p>Released <?= (new DateTimeImmutable($date))->format('Y-m-d') ?></p>
            <div class="pagination mt-4">
                <div class="page-item">
                    <a href="<?= $this->url('security.pages', ['action' => 'advisories']) ?>" class="page-link rounded-4 gradient-background">
                        <i class="bi bi-arrow-left"></i>
                        <span class="sr-only">Back to advisories</span>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-sm-12 order-1 order-sm-2">
        <?php $this->insert('security::menu') ?>
        </div>
    </div>
</div>
