<?php $this->layout('layout::default', ['title' => 'Security Advisories']) ?>

<div class="container">
    <div class="row align-items-start mt-5">
        <div class="col-md-8 col-sm-12 order-2 order-sm-1 mt-5 mt-s-0 mt-md-0 mt-lg-0 mt-xl-0">
            <h2>Security Advisory: <?= $advisory ?></h2>

            <?= $body ?>

            <div class="spacing"></div>
            <div class="hline"></div>

            <p>Released <?= date('Y-m-d', $date) ?></p>
            <p><a href="/security/advisories"><i class="fa fa-chevron-left"></i> Back to advisories</a></p>

        </div>

        <div class="col-md-4 col-sm-12 order-1 order-sm-2">
        <?php $this->insert('security::menu') ?>
        </div>
    </div>
</div>
