<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 */

$links = [
    '/security'            => 'Overview',
    '/security/advisories' => 'Advisories',
    '/security/feed'       => 'Feed',
];
$path = parse_url($this->serverurl(), PHP_URL_PATH);
?>

<div class="card border border-primary rounded-4">
    <ul class="card-body nav flex-column">
    <?php foreach ($links as $url => $title) : ?>
        <li class="nav-item<?= ($path === $url) ? ' active' : '' ?>">
            <a href="<?= $url ?>">
            <?php if ('/security/feed' === $url) : ?>
                <i class="bi-rss-fill"></i>
            <?php else : ?>
                <span class="glyphicon glyphicon-chevron-right"></span>
            <?php endif ?>
                <?= $title ?>
            </a>
        </li>
    <?php endforeach ?>
    </ul>
</div>

<div class="card border border-primary rounded-4 mt-5">
    <div class="card-body">
        <p class="card-text"><i class="bi-bug-fill"></i> Have you identified a security vulnerability?</p>

        <p>Please report it to us at <a href="mailto:security@getlaminas.org">security@getlaminas.org</a></p>
    </div>
</div>
