<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 */
?>

<footer class="footer">
    <div class="row">
        <div class="col-md-12 text-center">
            <a class="footer__button" href="#page-top">
                <i class="bi-arrow-up-square-fill" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    <div id="footer-section" class="m-auto row">
        <div class="col-md-6">
            <h5>Laminas</h5>
            <ul>
                <li>Maintenance Overview <a href="<?= $this->url('app.packages-maintenance-status') ?>">Current maintenance status of Laminas & Mezzio packages</a></li>
                <li>Components <a href="https://docs.laminas.dev/components" target="_blank">Components for enterprise applications</a></li>
                <li>Mezzio <a href="https://docs.mezzio.dev/" target="_blank">PSR-15 middleware in minutes</a></li>
                <li>MVC <a href="https://docs.laminas.dev/mvc" target="_blank">MVC for enterprise applications</a></li>
            </ul>
        </div>

        <div class="col-md-6">
            <div>
                <div>
                    Hosting sponsored by the <a title="platform.sh" href="https://platform.sh/?medium=referral&utm_campaign=sponsored_sites&utm_source=laminas_getlaminas_org"><img class="platformsh-logo" src="https://platform.sh/logos/redesign/Platformsh_logo_white@2x.png" alt="platform.sh logo" style="padding: 0 3px 0 3px;height: 1.1em; vertical-align: text-bottom;"/></a> <a href="https://platform.sh/?medium=referral&utm_campaign=sponsored_sites&utm_source=laminas_getlaminas_org">PHP Cloud Hosting</a> Service
                </div>
                <div class="fw-bolder">The Linux Foundation's only PHP project.</div>
            </div>

            <div class="row">
                <div class="footer-col">
                    <h4 class="footer__headline">Support</h4>
                    <ul class="support__list">
                        <li class="support__list-item col-md-4">
                            <a href="https://discourse.laminas.dev" class="support__link" title="Forum" target="_blank"><i class="bi-chat-text-fill"></i></a>
                        </li>
                        <li class="support__list-item col-md-4">
                            <a href="https://laminas.dev/chat" class="support__link" title="Chat" target="_blank"><i class="bi-slack"></i></a>
                        </li>
                        <li class="support__list-item col-md-4">
                            <a href="https://github.com/laminas" class="support__link" title="Github" target="_blank"><i class="bi-github"></i></a>
                        </li>
                        <li class="support__list-item col-md-4">
                            <a href="https://phpc.social/@getlaminas" class="support__link" title="Mastodon" target="_blank"><i class="bi-mastodon"></i></a>
                        </li>
                        <li class="support__list-item col-md-4">
                            <a href="<?= $this->url('blog.feed', ['type' => 'rss']) ?>" class="support__link" title="Blog feed" target="_blank"><i class="bi-rss"></i></a>
                        </li>
                        <li class="support__list-item col-md-4">
                            <a href="<?= $this->url('security.pages', ['action' => 'feed']) ?>" class="support__link" title="Security feed" target="_blank"><i class="bi-rss-fill"></i></a>
                        </li>
                    </ul>
                </div>

                <div class="footer-col">
                    <h4 class="footer__headline">License</h4>
                    <p>Code licensed under BSD 3-Clause.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            &copy; <?= date('Y') ?> by <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
        </div>
    </div>
</footer>
