<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 */
?>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <a class="footer__button" href="#page-top">
                    <i class="bi bi-chevron-up" aria-hidden="true"></i>
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <h5 class="text-white">Laminas – The Linux Foundation's only PHP project</h5>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <ul>
                    <li>Mezzio <a href="https://docs.mezzio.dev/">PSR-15 middleware in minutes</a></li>
                    <li>Laminas Components <a href="https://docs.laminas.dev/components">Enterprise-ready PHP components</a></li>
                    <li>Maintenance Overview <a href="<?= $this->url('app.packages-maintenance-status') ?>">Current maintenance status of Laminas &amp; Mezzio packages</a></li>
                    <li>Laminas Integrations <a href="<?= $this->url('app.integrations') ?>">List of packages using Laminas & Mezzio components</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <p>
                    Hosting sponsored by the <br><a title="upsun" href="https://upsun.com/?medium=referral&utm_campaign=sponsored_sites&utm_source=laminas_getlaminas_org"><img src="/images/upsun-logo.png" alt="upsun logo" style="margin: -1em; padding: 0 3px 0 3px;height: 3em; vertical-align: text-bottom;"/></a><br><a href="https://upsun.com/?medium=referral&utm_campaign=sponsored_sites&utm_source=laminas_getlaminas_org">PHP Cloud Hosting</a> Service
                </p>
             </div>
        </div>

        <div class="row mt-5">
            <div class="col-md-4">
                <h5 class="footer__headline text-white">Support</h5>
                <ul class="support__list">
                    <li class="support__list-item">
                        <a href="https://discourse.laminas.dev" class="support__link" title="Forum"><i class="bi-chat-text-fill"></i><span class="visually-hidden">Laminas &amp; Mezzio Forum</span></a>
                    </li>
                    <li class="support__list-item">
                        <a href="https://laminas.dev/chat" class="support__link" title="Chat"><i class="bi-slack"></i><span class="visually-hidden">Laminas Community Slack</span></a>
                    </li>
                    <li class="support__list-item">
                        <a href="https://github.com/laminas" class="support__link" title="Github"><i class="bi-github"></i><span class="visually-hidden">Laminas GitHub Organisation Page</span></a>
                    </li>
                    <li class="support__list-item">
                        <a href="https://phpc.social/@getlaminas" class="support__link" title="Mastodon"><i class="bi-mastodon"></i><span class="visually-hidden">Laminas on Mastodon</span></a>
                    </li>
                    <li class="support__list-item">
                        <a href="<?= $this->url('blog.feed', ['type' => 'rss']) ?>" class="support__link" title="Blog feed"><i class="bi-rss"></i><span class="visually-hidden">Blog article RSS Feed</span></a>
                    </li>
                    <li class="support__list-item">
                        <a href="<?= $this->url('security.pages', ['action' => 'feed']) ?>" class="support__link" title="Security feed">
                            <i class="bi-rss-fill"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <h5 class="footer__headline text-white">License</h5>
                <p>
                    Code licensed under
                    <a href="https://github.com/laminas/technical-steering-committee/blob/main/LICENSE.md" title="Full license text on GitHub">BSD 3-Clause</a>.
                </p>
            </div>
            <div class="col-md-4">
                <h5 class="footer__headline text-white">Copyright</h5>
                <p>&copy; <?= date('Y') ?> <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.</p>
            </div>
        </div>
    </div>
</footer>
