<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 */
$currentUrl = rtrim(parse_url($this->serverurl(), PHP_URL_PATH), '/');

$isCurrentRoute = function (string $routeName) use ($currentUrl): bool {
    $routeUrl = rtrim($this->url($routeName), '/');
    return $currentUrl === $routeUrl;
};

$isRouteSubpath = function (string $routeName) use ($currentUrl): bool {
    $routeUrl = rtrim($this->url($routeName), '/') . '/';
    $currentUrl .= '/';
    return str_starts_with($currentUrl, $routeUrl);
};
?>
<nav class="navbar navbar-expand-md bg-body fixed-top shadow">
    <div id="main-navbar" class="container">
        <a class="navbar-brand" href="/">
            <img src="/images/logo/laminas-foundation-rgb.svg" alt="Laminas Project"/>
        </a>

        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle<?= $isRouteSubpath('about.overview') || $isRouteSubpath('security') ? ' active' : '' ?>"
                       href="#"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">About</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item<?= $isCurrentRoute('about.overview') ? ' active' : '' ?>" href="<?= $this->url('about.overview') ?>">Overview</a>
                        <a class="dropdown-item<?= $isCurrentRoute('about.tsc') || $isCurrentRoute('about.join') ? ' active' : '' ?>" href="<?= $this->url('about.tsc') ?>">Technical Steering Committee</a>
                        <a class="dropdown-item<?= $isCurrentRoute('about.foundation') ? ' active' : '' ?>" href="<?= $this->url('about.foundation') ?>">About the Foundation</a>
                        <a class="dropdown-item<?= $isRouteSubpath('security') ? ' active' : '' ?>" href="<?= $this->url('security') ?>">Security</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link<?= $isRouteSubpath('blog') ? ' active' : '' ?>"
                       href="<?= $this->url('blog') ?>">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://docs.laminas.dev" target="_blank" >Docs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link<?= $isRouteSubpath('community.participate') ? ' active' : '' ?>"
                       href="<?= $this->url('community.participate') ?>">Community</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link pe-0 dropdown-toggle<?= $isRouteSubpath('app.support') || $isRouteSubpath('app.commercial-vendor-program') ? ' active' : '' ?>"
                       href="<?= $this->url('app.support') ?>"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">Support Laminas</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item<?= $isCurrentRoute('app.support') ? ' active' : '' ?>" href="<?= $this->url('app.support') ?>">Overview</a>
                        <a class="dropdown-item" href="https://crowdfunding.lfx.linuxfoundation.org/projects/laminas-project" target="_blank">Sponsor Laminas Development <i class="bi-box-arrow-up-right"></i></a>
                        <a class="dropdown-item<?= $isCurrentRoute('app.commercial-vendor-program') ? ' active' : '' ?>" href="<?= $this->url('app.commercial-vendor-program') ?>">Commercial Vendor Program</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
