<?php
declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var object{
 *     is_first: bool,
 *     is_last: bool,
 *     previous: ?int,
 *     next: ?int,
 *     last: int,
 *     pages: list<array{current: bool, number: int}>,
 *     base_path: string
 * } $pagination
 */
?>
<?php if (count($pagination->pages) > 1): ?>
<div class="row justify-content-start">
  <nav>
        <?php if (! $pagination->is_first) : ?>
            <ul class="pagination justify-content-between">
        <?php else: ?>
                <ul class="pagination justify-content-end">
        <?php endif ?>

        <?php if (isset($pagination->previous)) : ?>
            <li class="page-item"><a href="<?= $pagination->base_path ?>?page=<?= $pagination->previous ?>" class="page-link rounded-4 gradient-background"><i class="bi bi-arrow-left"></i><span class="sr-only">Previous</span></a></li>
        <?php endif ?>

        <?php if (isset($pagination->next)) : ?>
            <li class="page-item"><a href="<?= $pagination->base_path ?>?page=<?= $pagination->next ?>" class="page-link rounded-4 gradient-background"><span class="sr-only">Next</span><i class="bi bi-arrow-right"></i></a></li>
        <?php endif ?>
    </ul>
  </nav>
</div>
<?php endif ?>