<?php
declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var object{
 *     is_first: bool,
 *     is_last: bool,
 *     previous: ?int,
 *     next: ?int,
 *     last: int,
 *     pages: list<array{current: bool, number: int}>,
 *     base_path: string
 * } $pagination
 */
?>
<?php if (count($pagination->pages) > 1): ?>
<div class="row justify-content-start">
  <nav class="col-md-6">
    <ul class="pagination">
        <?php if (! $pagination->is_first) : ?>
        <li class="page-item"><a href="<?= $pagination->base_path ?>" class="page-link">&lt;&lt;<span class="sr-only">First</span></a></li>
        <?php endif ?>

        <?php if (isset($pagination->previous)) : ?>
        <li class="page-item"><a href="<?= $pagination->base_path ?>?page=<?= $pagination->previous ?>" class="page-link">&lt;<span class="sr-only">Previous</span></a></li>
        <?php endif ?>

        <?php foreach ($pagination->pages as $page) : ?>
            <?php if ($page['current']) : ?>
        <li class="page-item active"><a href="#" class="page-link"><?= $page['number'] ?></a></li>
            <?php else : ?>
        <li class="page-item"><a href="<?= $pagination->base_path ?>?page=<?= $page['number'] ?>" class="page-link"><?= $page['number'] ?></a></li>
            <?php endif ?>
        <?php endforeach ?>

        <?php if (isset($pagination->next)) : ?>
        <li class="page-item"><a href="<?= $pagination->base_path ?>?page=<?= $pagination->next ?>" class="page-link"><span class="sr-only">Next</span>&gt;</a></li>
        <?php endif ?>

        <?php if (! $pagination->is_last) : ?>
        <li class="page-item"><a href="<?= $pagination->base_path ?>?page=<?= $pagination->last ?>" class="page-link"><span class="sr-only">Last</span>&gt;&gt</a></li>
        <?php endif ?>
    </ul>
  </nav>
</div>
<?php endif ?>