<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var stdClass                        $pagination
 */

$this->layout('layout::default', ['title' => 'Blog']);

$this->push('styles');
echo $this->fetch('blog::styles');
$this->end();

$this->push('scripts');
echo $this->fetch('blog::scripts');
$this->end();
?>
<section class="blog container p-0">
    <div class="row align-items-start mt-5">
        <div class="col">
            <h1 class="page-header">
                Blog
                <?php if (isset($tag)) : ?>
                    <small>Tag: <?= $this->escapeHtml($tag) ?></small>
                <?php endif ?>
            </h1>
        </div>
    </div>

    <?php if (empty($posts)) : ?>
        <div class="row mt-5"><p class="col text-center">No posts found.</p></div>

    <?php else : ?>
        <div class="blog-listing">
            <?php /** @var GetLaminas\Blog\BlogPost $post */
            foreach ($posts as $post) : ?>
                <div class="col-lg-4 col-md-6 col-sm-12 mt-3 h-entry blog-card card">
                    <div class="blog-card-content">
                        <h4 class="blog-header"><?= $this->escapeHtml($post->title) ?></h4>

                        <div class="entry body p-summary"><?= $post->body ?></div>

                        <a class="blog-continue-reading" href="<?= $this->postUrl($post) ?>">
                            Continue reading
                            <i class="bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            <?php endforeach ?>
        </div>

        <div class="mt-4">
            <?php $this->insert('partials::pagination', ['pagination' => $pagination]) ?>
        </div>

    <?php endif ?>
    <a href="https://github.com/laminas/getlaminas.org/blob/master/ADD_BLOG_ENTRY.md" target="_blank">
        Submit a blog post by following these instructions.
    </a>
</section>
