<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var GetLaminas\Blog\BlogPost        $post
 */

$this->layout('layout::default', [
    'title'                => $this->escapeHtml($post->title),
    'opengraphImage'       => $post->openGraphImage,
    'opengraphDescription' => $post->openGraphDescription,
]);

$this->start('styles');
$this->insert('blog::styles');
$this->stop();

$this->push('scripts');
$this->insert('blog::scripts');
$this->end();

?>
<div class="single-entry h-entry container">
    <div class="row align-items-start mt-5">
        <div class="col">
            <h1><a href="<?= $this->url('blog') ?>">Blog</a></h1>
        </div>
    </div>

    <div class="row align-items-start mt-5">
        <article class="col-md-8 blog">
            <h2 class="p-name"><?= $this->escapeHtml($post->title) ?></h2>

            <div class="e-content">
            <?= $post->body ?>

            <?= $post->extended ?>
            </div>

            <p>
                <a href="<?= $this->url('blog') ?>">
                    <i class="bi-arrow-left"></i>
                    Back to blog posts
                </a>
            </p>
        </article>

        <aside class="col-md-4 d-sm-block sidebar blog">
            <p>
                Written on <time class="dt-published" datetime="<?= $this->formatDateRfc($post->created) ?>"><?= $this->formatDate($post->created) ?></time><?= $post->author ? sprintf(' by %s', $this->postAuthor($post)) : '' ?>.

                <?php if ($post->updated) : ?>
                <br />Last updated on <time class="dt-updated" datetime="<?= $this->formatDateRfc($post->updated) ?>"><?= $this->formatDate($post->updated) ?></time>.
                <?php endif ?>
            </p>
            <?php if ($post->toc): ?>
                <h5>Table of Contents</h5>
                <?= $post->toc ?>
            <?php endif ?>
        </aside>
    </div>
</div>
