<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 */
$this->layout('layout::default', ['title' => '404 Not Found']);
?>

<div class="hero-container hero-404 mb-4">
    <div class="container-lg bg-body-tertiary text-body-tertiary text-center bg-opacity-75 py-5 px-3 px-md-5">
        <h1>Ooops!</h1>

        <h2>This is awkward.</h2>
    </div>
</div>

<div class="container-lg">
    <div class="row justify-content-center mt-5">
        <div class="col-sm-8 col-xs-12 text-center">
            <p>We encountered a 404 Not Found error.</p>

            <p>
                You are looking for something that doesn't exist or may have
                moved. Check out one of the links on this page or head back to
                <a href="/">Home</a>.
            </p>
        </div>
    </div>
</div>
