<?php $this->layout('layout::default', ['title' => '404 Not Found']) ?>

<div class="container">
    <div class="row mt-5 jumbotron jumbotron-404 text-center">
        <div class="lead-box">
            <h1 class="text-primary">Ooops!</h1>

            <h2 class="text-primary">This is awkward.</h2>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-sm-8 col-xs-12 text-center">
            <p>We encountered a 404 Not Found error.</p>

            <p>
                You are looking for something that doesn't exist or may have
                moved. Check out one of the links on this page or head back to
                <a href="/">Home</a>.
            </p>
        </div>
    </div>
</div>
