<?php $this->layout('layout::default', ['title' => 'Community']) ?>

<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h1>Community</h1>
        </div>
    </div>

    <div class="row row-cols-1 row-cols-md-3">
        <div class="col mb-4">
            <div class="card h-100 border border-primary rounded">
                <div class="card-header bg-primary text-white w-auto">
                    On GitHub
                </div>

                <ul class="nav flex-column card-body">
                    <li class="nav-item"><a href="https://github.com/laminas">Laminas organization</a></li>
                    <li class="nav-item"><a href="https://github.com/mezzio">Mezzio organization</a></li>
                    <li class="nav-item"><a href="https://github.com/laminas-api-tools">API Tools organization</a></li>
                </ul>
            </div>
        </div>

        <div class="col mb-4">
            <div class="card h-100 border border-primary rounded">
                <div class="card-header bg-primary text-white w-auto">
                    Chat
                </div>

                <ul class="nav flex-column card-body">
                    <li class="nav-item"><a href="https://zendframework.slack.com">Visit the Slack</a></li>
                    <li class="nav-item"><a href="https://join.slack.com/t/zendframework/shared_invite/enQtNTkyMzExNzAxMzMwLWU3MjI2MGNlM2EyNWQzZDg4NTMzNDM2NzQ1ZDU2ZDJiNDVhZDQyZDczOThjNGIwOWNiODQ0YzE1NTA3NGU2YTA">Need an invite?</a></li>
                </ul>
            </div>
        </div>

        <div class="col mb-4">
            <div class="card h-100 border border-primary rounded">
                <div class="card-header bg-primary text-white w-auto">
                    Forums
                </div>

                <ul class="nav flex-column card-body">
                    <li class="nav-item"><a href="https://discourse.laminas.dev">Visit our Discourse</a></li>
                </ul>
            </div>
        </div>

    </div>
</div>
