<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 */

$this->layout('layout::default', ['title' => 'Community']);
?>

<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h1>Community</h1>
        </div>
    </div>

    <div class="row row-cols-1 row-cols-md-3">
        <div class="col mb-4">
            <div class="card h-100 border border-primary rounded">
                <div class="card-header bg-primary text-white w-auto">
                    <i class="bi-github"></i>
                    On GitHub
                </div>

                <ul class="nav flex-column card-body">
                    <li class="nav-item">
                        <a href="https://github.com/laminas">
                            <i class="bi-box-arrow-up-right"></i>
                            Laminas organization
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://github.com/mezzio">
                            <i class="bi-box-arrow-up-right"></i>
                            Mezzio organization
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://github.com/laminas-api-tools">
                            <i class="bi-box-arrow-up-right"></i>
                            API Tools organization
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col mb-4">
            <div class="card h-100 border border-primary rounded">
                <div class="card-header bg-primary text-white w-auto">
                    <i class="bi-slack"></i>
                    Chat
                </div>

                <ul class="nav flex-column card-body">
                    <li class="nav-item">
                        <a href="https://laminas.slack.com">
                            <i class="bi-box-arrow-up-right"></i>
                            Visit the Slack
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://join.slack.com/t/laminas/shared_invite/enQtNTkyMzExNzAxMzMwLWU3MjI2MGNlM2EyNWQzZDg4NTMzNDM2NzQ1ZDU2ZDJiNDVhZDQyZDczOThjNGIwOWNiODQ0YzE1NTA3NGU2YTA">
                            <i class="bi-box-arrow-up-right"></i>
                            Need an invite?
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col mb-4">
            <div class="card h-100 border border-primary rounded">
                <div class="card-header bg-primary text-white w-auto">
                    <i class="bi-chat-text-fill"></i>
                    Forums
                </div>

                <ul class="nav flex-column card-body">
                    <li class="nav-item">
                        <a href="https://discourse.laminas.dev">
                            <i class="bi-box-arrow-up-right"></i>
                            Visit our Discourse
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
</div>
