<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var string                          $title
 */
?>

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->insert('partials::favicon') ?>

    <title><?= $this->e($title) ?> - Laminas Project - Enterprise PHP Framework</title>

    <link rel="stylesheet" href="/<?= $this->assets('css/laminas.css') ?>">
    <?= $this->section('stylesheets') ?>
</head>
<body id="page-top" class="h-100 d-flex flex-column">
    <nav class="navbar navbar-expand-sm navbar-light bg-white fixed-top shadow"><div class="container">
        <!-- Brand -->
        <a class="navbar-brand" href="/">
            <img src="/images/logo/laminas-foundation-rgb.svg" alt="Laminas Project" />
        </a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('about.overview') ?>">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('blog') ?>">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://docs.laminas.dev">Docs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('community.participate') ?>">Community</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('app.support') ?>">Support Laminas</a>
                </li>
            </ul>
        </div>
    </div></nav>

    <main class="flex-grow-1">
        <?= $this->section('content') ?>
    </main>

    <?= $this->insert('partials::footer') ?>

    <script src="/<?= $this->assets('js/laminas.js') ?>"></script>
    <?= $this->section('javascript') ?>
</body>
</html>
