<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var string                          $title
 */
?>

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->insert('partials::favicon') ?>

    <title><?= $this->e($title) ?> - Laminas Project - Enterprise PHP Framework</title>

    <link rel="stylesheet" href="/<?= $this->assets('css/laminas.css') ?>">
    <?= $this->section('stylesheets') ?>
</head>
<body id="page-top" class="h-100 d-flex flex-column">
    <?= $this->insert('partials::navigation') ?>

    <main class="flex-grow-1">
        <?= $this->section('content') ?>
    </main>

    <?= $this->insert('partials::footer') ?>

    <script src="/<?= $this->assets('js/laminas.js') ?>"></script>
    <?= $this->section('javascript') ?>
</body>
</html>
