<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 * @var string                          $title
 * @var string|null                     $opengraphImage
 * @var string|null                     $opengraphDescription
 */

$opengraphImage       = $opengraphImage ?? "/images/opengraph/default.png";
$opengraphDescription = $opengraphDescription ?? "Laminas & Mezzio: enterprise-ready, open-source PHP components and middleware microframework. A community-supported, open-source continuation of Zend Framework.";
?>

<!DOCTYPE html>
<html lang="en" data-bs-theme="light" class="h-100">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->insert('partials::favicon') ?>

    <title><?= $this->e($title) ?> - Laminas Project - Enterprise PHP Components and Middleware Microframework</title>

    <!-- OpenGraph card -->
    <meta property="og:title" content="Laminas Project - <?= $this->e($title) ?>"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="<?= $this->serverurl() ?>">
    <meta property="og:image" content="<?= $opengraphImage ?>"/>
    <meta property="og:description" content="<?= $opengraphDescription ?>"/>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="/<?= $this->assets('css/laminas.css') ?>">
    <?= $this->section('stylesheets') ?>
</head>
<body id="page-top" class="h-100 d-flex flex-column">
    <?= $this->insert('partials::navigation') ?>

    <main class="flex-grow-1">
        <?= $this->section('content') ?>
    </main>

    <?= $this->insert('partials::footer') ?>

    <script src="/<?= $this->assets('js/laminas.js') ?>"></script>
    <?= $this->section('javascript') ?>
</body>
</html>
