#!/bin/sh
# Entrypoint script for php container.
set -e

# Copy CSS assets in public
cp -r /assets/css /var/www/public

# Add assets revision config to application
cp /assets/assets.json /var/www/data/

# Start application; run in foreground, as that's what Docker prefers
# Following is from the official docker-php-entrypoint
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

echo "Running php container using '$@'"
exec "$@"
