name: "Markdown files linting"

on:
  pull_request:
  push:
    branches:
    tags:

jobs:
  linting:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        - uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20
          with:
            config: '.markdownlint.json'
            globs: |
              **/*.md
              !README.md
              !LICENSE.md
              !COPYRIGHT.md
              !bootstrap
              !public
